In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr+2)
print(arr*3)
print(arr/2)

[3 4 5 6 7 8]
[ 3  6  9 12 15 18]
[0.5 1.  1.5 2.  2.5 3. ]


In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])
newarr = np.flip(arr)
print(newarr)
print()

x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

def getMostFreq(x):
  unique,count = np.unique(x,return_counts=True)
  mode = unique[np.argmax(count)]
  indices = np.where(x == mode)[0]
  return mode,indices

mode,indices = getMostFreq(x)
print("For array x:")
print("Most frequent element is: ",mode)
print("Indices: ",indices)
print()

mode,indices = getMostFreq(y)
print("For array y:")
print("Most frequent element is: ",mode)
print("Indices: ",indices)




[5 4 6 3 2 1]

For array x:
Most frequent element is:  1
Indices:  [0 5 7 8 9]

For array y:
Most frequent element is:  1
Indices:  [0 1 2]


In [3]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[0][1])
print(arr[2][0])

20
70


In [4]:
vis=np.linspace(10,100,25)

print('Array:',vis)

print('Dimension: ',vis.ndim)
print('Shape :',vis.shape)
print('Number of elements:',vis.size)
print('Data Type:',vis.dtype)
print('Total bytes: ',vis.nbytes)

transpose=vis.reshape(25,1)
print('Using reshape:')
print(transpose)
print()

print('Using T attribute:')
transpose=vis.T
print(transpose)
print()
print('Cannot use T attribute')

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimension:  1
Shape : (25,)
Number of elements: 25
Data Type: float64
Total bytes:  200
Using reshape:
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Using T attribute:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Cannot use T attribute


In [5]:
ucs420_vishard_mehta = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print(ucs420_vishard_mehta)
print()
print('Mean : ', np.mean(ucs420_vishard_mehta))
print()
print('Median : ', np.median(ucs420_vishard_mehta))
print()
print('Max : ', np.max(ucs420_vishard_mehta))
print()
print('Min : ',  np.min(ucs420_vishard_mehta))
print()
print('Unique elements: ', np.unique(ucs420_vishard_mehta))
print()

reshaped_ucs420_vishard_mehta=ucs420_vishard_mehta.reshape(4,3)
resized_ucs420_vishard_mehta=np.resize(ucs420_vishard_mehta,(2,3))
print("Reshaped: \n", reshaped_ucs420_vishard_mehta)
print()
print("Resized: \n", resized_ucs420_vishard_mehta)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean :  43.333333333333336

Median :  37.5

Max :  90

Min :  10

Unique elements:  [10 15 20 30 35 40 50 60 70 80 90]

Reshaped: 
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized: 
 [[10 20 30]
 [40 50 60]]
